version: '3.3'

services:
    app:
        build: ./docker/app
        container_name: monvestor_app
        volumes:
            - ./:/var/www/html
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
        networks:
            - monvestor-network

    nginx:
        container_name: monvestor_nginx
        image: nginx:stable-alpine
        ports:
            - "8082:80"
        volumes:
           - ./:/var/www/html
           - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - monvestor-network

    mysql:
        image: mysql
        container_name: monvestor_db
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USERNAME: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
        networks:
            - monvestor-network

networks:
    monvestor-network:
        driver: bridge